# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# For reference, see: https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brightspot Training
description: >- # this means to ignore newlines until "baseurl:"
  Brought to you by the Brightspot Delivery Team
baseurl: "/training" # the subpath of your site, e.g. /blog
url: "https://perfectsense.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: perfectsense
github:
  public: false

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

kramdown:
syntax_highlighter_opts:
  block:
    line_numbers: true

# Enable or disable heading anchors
heading_anchors: true
# Aux links for the upper right navigation
aux_links:
  "Brightspot Documentation":
    - "https://www.brightspot.com/documentation/"
  "Support Portal":
    - "https://perfectsense.atlassian.net/servicedesk/customer/portal/1"

logo: "/assets/images/brightspot-logo-200px.svg"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

#plugins:
# - jekyll-feed
#
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll.sh
  - README.md
include:
  - _pages
